config/routes.rb
Rails.application.routes.draw do

  root to: 'locations#index'
  resources :locations

end

app/models/location.rb
class Location < ActiveRecord::Base

  geocoded_by :address
  validates :address,  presence: true
  after_validation :geocode, :if => :address_changed?


 # validates :address,  presence: true
 # validates :longitude, :latitude, presence: true

  #after_validation :geocode, :if => :address_changed?
  #validates :address, :longitude, :latitude, presence: true
 # validates :address, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  Timezone::Configure.begin do |c|
    c.username = 'motolanilagoke@yahoo.com'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController


  def index
    redirect_to :controller=>'user_home', :action =>'index'
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    if params[:search].present?

      @locations = Location.near(params[:search], 50, :order => :distance)
    else
      @locations = Location.all
    end

  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    redirect_to :controller=>'locations', :action =>'index'
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create

    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:address, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def wikify(text)

    text.gsub!(/(\<wp\>(.*?)\<\/wp\>)/) do |m|
      n = m.gsub!(/(\<wp\>|<\/wp\>)/, '')
      link_to(n, "http://en.wikipedia.org/wiki/#{n}")
    end

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/home/index.erb
<h1> World Time</h1>

<p> Enter location</p>

<%= form_tag locations_path, :method => :get do %>
    <p>
      <%= text_field_tag :address, params[:address] %>
      <%= submit_tag "Search Near", :name => nil %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "WorldTime" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">WorldTime</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">

          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>BackFlip</h3>
            <ul class="nav nav-list">
              <li class="nav-header"></li>
              <li><%= link_to "HELP", "/path1"  %></li>
              <li><%= link_to "ABOUT US", "/path2"  %></li>
              <li><%= link_to "CONTACT US", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; BackFlip  2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Locations</h1>





<table>
  <thead>

    <tr>
      <table style="width: 94%">
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Current Time</th>
        <th>Daylight Savings</th>

      <th>wiki</th>

      <th colspan="5"></th>
      </table>
    </tr>
  </thead>

  <tbody>

    <% @locations.each do |location| %>

      <tr style="width: 100%">
          <table style="width: 100%">
          <td style="width: 13%"><%= location.address %></td>
          <td style="width: 13%"><%= location.latitude %></td>
            <td style="width: 17%"><%= location.longitude %></td>

            <td hidden> <%=time_zone = GeoNamesAPI::TimeZone.find(location.latitude,location.longitude)%></td>
            <td style="width: 27%"><%=time_zone.time %></td>


            <td style="width: 22%"><%=time_zone.dst?(Time.now)%> <%=image_tag("http://www.ikea.com/us/en/images/products/bondis-wall-clock-black__0096033_PE235389_S1.JPG")%></td>

            <td style="width: 20%"><%=link_to(location.address,"http://en.wikipedia.org/wiki/#{location.address}")%></td>
          <td><%= link_to 'Delete', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </table>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Nearby locations</h3>
<ul>
  <% for location in @location.nearbys(100) %>
      <li><%= link_to location.address, location %> (<%= location.distance.round(2) %> miles)</li>
  <% end %>
</ul>